services:
  - type: web
    name: fb-fanpage-insight
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: FB_HEADLESS
        value: "true"
      - key: TZ
        value: Asia/Ho_Chi_Minh
      - key: ADMIN_EMAIL
        value: admin@gmail.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: PAGE_ID
        sync: false
      - key: FB_PAGE_ACCESS_TOKEN
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
